### ISSUE TITLE
Can not locate xmpir64.dll

### ISSUE THREAD

**Issue by Memnarch** [wezeku/Mpir.NET#14]
After installing and starting my project, I get this exception:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Mpir.NET.mpir' threw an exception.
  Source=Mpir.NET
  StackTrace:
   at Mpir.NET.mpir.mpz_init_set_si(Int32 op)
   at Mpir.NET.mpz_t..ctor(Int32 op)
   at Mpir.NET.mpz_t.op_Implicit(Int32 value)
   at PiDemo.Program.<EnumPi>d__0.MoveNext() in C:\Users\<user>\source\repos\PiDemo\Program.cs:line 13
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PiDemo.Program.Main(String[] args) in C:\Users\<user>\source\repos\PiDemo\Program.cs:line 58

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: MPIR: can't determine path to the xmpir64.dll

**Comment by l1t1** [comment]
I also got this error about xmpir64.dll

```
未经处理的异常:  System.TypeInitializationException: “Mpir.NET.mpir”的类型初始值设定项引发异常。 ---> System.Exception: MPIR: can't determine path to the xmpir64.dll
   在 Mpir.NET.mpir.LocateLibrary(String name)
   在 Mpir.NET.mpir.GetXMPIRLibraryPath()
   在 Mpir.NET.mpir.initialize_hxmpir()
   在 Mpir.NET.mpir..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Mpir.NET.mpir.mpz_init()
   在 Mpir.NET.mpz_t..ctor(UInt64 op)
   在 MpirSample.Main()
```
